version: 2

models:
  - name: stg_crm
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique

  - name: stg_service
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique
          - relationships:
              arguments:
                to: ref('stg_crm')
                field: customer_id

  - name: stg_billing
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique
          - relationships:
              arguments:
                to: ref('stg_crm')
                field: customer_id
      - name: total_charges
        data_tests:
          - not_null
      - name: contract
        data_tests:
          - accepted_values:
              arguments:
                values: ['Month-to-month', 'One year', 'Two year']

  - name: stg_churn_label
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique
          - relationships:
              arguments:
                to: ref('stg_crm')
                field: customer_id
      - name: churn_j30
        data_tests:
          - accepted_values:
              arguments:
                values: [0, 1]
                quote: false